package pl.riscosoftware.pak;

/**
 * This class was automatically generated by the data modeler tool.
 */
 
public class Address implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "ADDRESS_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "ADDRESS_ID_SEQ", name = "ADDRESS_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label(value = "Ulica")
   private java.lang.String street;

   private java.lang.String city;

   private java.lang.String postalCode;

   public Address()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getStreet()
   {
      return this.street;
   }

   public void setStreet(java.lang.String street)
   {
      this.street = street;
   }

   public java.lang.String getCity()
   {
      return this.city;
   }

   public void setCity(java.lang.String city)
   {
      this.city = city;
   }

   public java.lang.String getPostalCode()
   {
      return this.postalCode;
   }

   public void setPostalCode(java.lang.String postalCode)
   {
      this.postalCode = postalCode;
   }

   public Address(java.lang.Long id, java.lang.String street,
         java.lang.String city, java.lang.String postalCode)
   {
      this.id = id;
      this.street = street;
      this.city = city;
      this.postalCode = postalCode;
   }
   
     public String toString() {
         return id+" | "+
         street+" | "+
         city+" | "+
         postalCode+" | ";
     }

}