package pl.riscosoftware.pak;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Convenant implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "CONVENANT_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "CONVENANT_ID_SEQ", name = "CONVENANT_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("Nazwa")
   private java.lang.String name;

   @org.kie.api.definition.type.Label("Spełnione")
   private boolean checked;

   @org.kie.api.definition.type.Label(value = "Warto\u015B\u0107")
   private java.lang.String value;

   public Convenant()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public boolean isChecked()
   {
      return this.checked;
   }
   
      public boolean getChecked()
   {
      return this.checked;
   }

   public void setChecked(boolean checked)
   {
      this.checked = checked;
   }

   public java.lang.String getValue()
   {
      return this.value;
   }

   public void setValue(java.lang.String value)
   {
      this.value = value;
   }

   public Convenant(java.lang.Long id, java.lang.String name, boolean checked,
         java.lang.String value)
   {
      this.id = id;
      this.name = name;
      this.checked = checked;
      this.value = value;
   }

}