package pl.riscosoftware.pak;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "CUSTOMER_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "CUSTOMER_ID_SEQ", name = "CUSTOMER_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("Imię")
   private java.lang.String name;

   @org.kie.api.definition.type.Label("Nazwisko")
   private java.lang.String surname;

   @org.kie.api.definition.type.Label("Pesel")
   private java.lang.String pesel;

   @org.kie.api.definition.type.Label("Numer dowodu")
   private java.lang.String idNumber;

   @org.kie.api.definition.type.Label(value = "Adres")
   private pl.riscosoftware.pak.Address address;

   public Customer()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getSurname()
   {
      return this.surname;
   }

   public void setSurname(java.lang.String surname)
   {
      this.surname = surname;
   }

   public java.lang.String getPesel()
   {
      return this.pesel;
   }

   public void setPesel(java.lang.String pesel)
   {
      this.pesel = pesel;
   }

   public java.lang.String getIdNumber()
   {
      return this.idNumber;
   }

   public void setIdNumber(java.lang.String idNumber)
   {
      this.idNumber = idNumber;
   }

   public String toString()
   {
      return id + " | " +
            name + " | " +
            pesel + " | " +
            idNumber + " | " +
            address + " | ";
   }

   public pl.riscosoftware.pak.Address getAddress()
   {
      return this.address;
   }

   public void setAddress(pl.riscosoftware.pak.Address address)
   {
      this.address = address;
   }

   public Customer(java.lang.Long id, java.lang.String name,
         java.lang.String surname, java.lang.String pesel,
         java.lang.String idNumber, pl.riscosoftware.pak.Address address)
   {
      this.id = id;
      this.name = name;
      this.surname = surname;
      this.pesel = pesel;
      this.idNumber = idNumber;
      this.address = address;
   }
}