package pl.riscosoftware.pak;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Document implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "DOCUMENT_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "DOCUMENT_ID_GENERATOR", sequenceName = "DOCUMENT_ID_SEQ")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("Nazwa")
   private java.lang.String name;

   @org.kie.api.definition.type.Label("Załączony")
   private boolean checked;

   private java.lang.String data;

   public Document()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public boolean isChecked()
   {
      return this.checked;
   }

   public void setChecked(boolean checked)
   {
      this.checked = checked;
   }

   public java.lang.String getData()
   {
      return this.data;
   }

   public void setData(java.lang.String data)
   {
      this.data = data;
   }

   public Document(java.lang.Long id, java.lang.String name, boolean checked,
         java.lang.String data)
   {
      this.id = id;
      this.name = name;
      this.checked = checked;
      this.data = data;
   }

}