package pl.riscosoftware.pak;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Tranche implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long id;
   private java.util.Date date;

   public Tranche()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.util.Date getDate()
   {
      return this.date;
   }

   public void setDate(java.util.Date date)
   {
      this.date = date;
   }

   public Tranche(java.lang.Long id, java.util.Date date)
   {
      this.id = id;
      this.date = date;
   }

}