package demo.perstest;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class PersTest implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "PERSTEST_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "PERSTEST_ID_SEQ", name = "PERSTEST_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("Nazwa")
   private java.lang.String name;

   @org.kie.api.definition.type.Label("Ilość")
   private int quantity;

   @org.kie.api.definition.type.Label(value = "Potwierdzone")
   private java.lang.Boolean checked;

   public PersTest()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public int getQuantity()
   {
      return this.quantity;
   }

   public void setQuantity(int quantity)
   {
      this.quantity = quantity;
   }

   public java.lang.Boolean getChecked()
   {
      return this.checked;
   }

   public void setChecked(java.lang.Boolean checked)
   {
      this.checked = checked;
   }

   public PersTest(java.lang.Long id, java.lang.String name, int quantity,
         java.lang.Boolean checked)
   {
      this.id = id;
      this.name = name;
      this.quantity = quantity;
      this.checked = checked;
   }

}